apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  completions: {{ .Values.completions }}
  parallelism: {{ .Values.parallelism }}
  template:
    spec:
      serviceAccountName: "{{ .Values.appName }}-sa"
      containers:
        - image: "{{ .Values.imageName }}"
          name: {{ .Values.appName }}-{{ randAlphaNum 5 | lower}}
          env:
          - name: POD_STATUS
            value: {{ .Values.podStatus }}
      restartPolicy: Never
