apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.appName }}-sa"
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Values.appName }}-cluster-role"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Values.appName }}-cluster-role-binding"
subjects:
- kind: ServiceAccount
  name: "{{ .Values.appName }}-sa"
  namespace: default
roleRef:
  kind: ClusterRole
  name: "{{ .Values.appName }}-cluster-role"
  apiGroup: rbac.authorization.k8s.io
